version: "3.10"

services:
  backend:
    image: localhost:5000/backend:${DOCKER_IMAGE_TAG_CI}
    build:
      args:
        - RUN_POETRY_INSTALL_AT_BUILD_TIME=true
      context: ../../
      dockerfile: environments/Dockerfile.backend
    tty: true
    volumes:
        - ../../applications/backend:/home/challenger/backend
  
  frontend:
    image: localhost:5000/frontend:${DOCKER_IMAGE_TAG_CI}
    build:
      args:
        - RUN_POETRY_INSTALL_AT_BUILD_TIME=true
      context: ../../
      dockerfile: environments/Dockerfile.frontend
    tty: true
    volumes:
        - ../../applications/frontend:/home/challenger/frontend