version: "3.8"

services:
  backend:
    build:
      args:
        - UID=${HOST_UID-1000}
        - GID=${HOST_GID-1000}
      context: ../../
      dockerfile: environments/Dockerfile.backend
    tty: true
    volumes:
        - ../../applications/backend:/home/challenger/backend
    ports:
        - 8000:8000
  
  frontend:
    build:
      args:
        - UID=${HOST_UID-1000}
        - GID=${HOST_GID-1000}
      context: ../../
      dockerfile: environments/Dockerfile.frontend
    tty: true
    volumes:
        - ../../applications/frontend:/home/challenger/frontend
    ports:
        - 8501:8501
